### PR TITLE
Update Wash to 0.7.0

### PR DESCRIPTION
**Pull request by ekinanp**
Signed-off-by: Enis Inan <enis.inan@puppet.com>

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This will only apply to the next release. So we shouldn't merge it until we also bump the release version.

**Comment by ekinanp** [comment]
Is this ready for merge now that 0.7.0 is out?

**Comment by MikaelSmith** [comment]
Should include the version bump to 0.7.0 in the same PR.

**Comment by ekinanp** [comment]
Ah that's what you meant. Sure

**Pull request merged**
