### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by MikaelSmith**
Identify owners of specific release artifacts.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@puppetlabs/pdk @puppetlabs/bolt this look good to you?

**Comment by nicklewis** [comment]
I think the last match takes precedence (not the most specific match), so this will assign you to everything. Looks good to me. :+1:

**Comment by MikaelSmith** [comment]
I was hoping it would ping individual teams on their part, and also me on everything.

**Comment by nicklewis** [comment]
I _think_ in that case, the `*` line should be at the top and you need to add your name to every other line.

**Comment by MikaelSmith** [comment]
Guess I needed to read more closely.

**Comment by MikaelSmith** [comment]
I'm fine just being the fallback.

**Pull request merged**
